### ISSUE TITLE
Images breaking (just for multi?)

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace#193]
Images are not working for e.g.

https://kitspace.org/boards/github.com/eulerlab/open-visual-stimulator/boards/mosfet_circuit/

- is: `https://raw.githubusercontent.com/eulerlab/open-visual-stimulator/master/mofset_circuit_rendering.png?raw=true`
- should be: `https://raw.githubusercontent.com/eulerlab/open-visual-stimulator/master/boards/mosfet_circuit/mofset_circuit_rendering.png?raw=true`

I believe it's an issue with READMEs not being processed correctly for `multi`. @SDBowen can you take a look at it?

**Comment by SDBowen** [comment]
Who implemented this buggy multi repo feature! :sweat_smile: 

I will work on it. I think it is coming from the repo path in the `makeReadme.js`. 

https://github.com/kitspace/kitspace/blob/1102295d99ddf6cd94cd5fb52a313b2914af9465/tasks/page/makeReadme.js#L29
