### ISSUE TITLE
Browser detection broken on dev site on some versions of Chrome

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace#199]
As noticed in #198 it seems Chrome browser can be detected as incompatible with 1-click BOM. That's an issue!

Browser detection happens here: https://github.com/kitspace/kitspace/blob/master/src/buy_parts/install_prompt.jsx#L32

**Comment by kasbah** [comment]
I can't reproduce this with Chrome on Ubuntu. @SDBowen can you log what you get in a console on your chrome for `navigator.userAgent` and from `version` in the function above?

**Comment by SDBowen** [comment]
``navigator.userAgent``:
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"

``version``:
Chrome 77

It seems I only get this while running Kitspace locally. On the live site, I do not have an issue.

![Screenshot from 2019-10-26 12-12-50](https://user-images.githubusercontent.com/22715037/67618053-fc122900-f7e9-11e9-8482-2694bd1324bf.png)

**Comment by kasbah** [comment]
Ok yeah, this is actually as expected as we can't add localhost as a site the published extension can have access to.
