### ISSUE TITLE
Link to OSHPark

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace#201]
Oshpark have donated to our Open Collective so we should link to them ASAP. 

```
https://oshpark.com/import?url=URLFORTHEGERBERS
```

Logo:
![image](https://user-images.githubusercontent.com/206854/67440755-1c779300-f5f2-11e9-95ac-a5786b774c2f.png)

**Comment by nm-t** [comment]
It looks like OSHPark is already being linked to? Just with a different logo!

**Comment by kasbah** [comment]
Sorry I wasn't more clear. OSHPark should be added next to Aisler, PCBWay and RoyalCircuits, on the project pages. 
![image](https://user-images.githubusercontent.com/206854/67476736-80c93f80-f650-11e9-801e-a9447acdfe72.png)

This is also further complicated by work in progress on #198.
