### ISSUE TITLE
Code split the vendor.js bundle

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace#265]
Vendor.js is currently pretty heavy, coming in at 2.55MB ungzipped. I believe most of that is due to the dependencies of the /submit app which a lot of people don't even look at. 

We should split out the dependencies of /submit into a separate bundle only loaded when people visit it. 

![image](https://user-images.githubusercontent.com/206854/83661986-d8546400-a5be-11ea-90cc-f93cf97f6a98.png)

@SDBowen maybe you'd be interested to look at this one when you have time?

**Comment by SDBowen** [comment]
Played around with this today, will open up a PR.

**Comment by kasbah** [comment]
This was done with #266
