### ISSUE TITLE
Integrate InteractiveHtmlBom functionality

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace#274]
I am looking for someone to help integrate the KiCad plugin [InteractiveHtmlBom](https://github.com/openscopeproject/InteractiveHtmlBom) (or functionality like it). I posted a job advert on Contextual Electronics forums:

https://forum.contextualelectronics.com/t/looking-for-a-python-js-kicad-web-dev/2988

**Comment by ian-ross** [comment]
If you go to https://kitspace-dev.skybluetrades.net you'll find a version of the site with really rough interactive HTML BOM pages on it. Any board that has a KiCad PCB file gets an "Interactive BOM" link (e.g. https://kitspace-dev.skybluetrades.net/boards/github.com/mattvenn/esp8266-breakout/). I've made a PR for discussion.
