### ISSUE TITLE
Bus Pirate board not getting an IBOM

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace#307]
@ian-ross Any ideas why this one is not getting an IBOM? https://kitspace.org/boards/github.com/kitspace-forks/bus_pirate/

**Comment by ian-ross** [comment]
Because it doesn't have a valid EAGLE board file. There's a file in there called `BusPirate-v3.6a-SSOP.brd`, but it's not a valid EAGLE file, as far as I can tell. All the other `*.brd` files I can find are XML files, while the Bus Pirate one is some random binary data.

**Comment by kasbah** [comment]
Oh right, it's the old EAGLE format.
