### ISSUE TITLE
Automatic update of the website when git repository changes

### ISSUE THREAD

**Issue by descampsa** [kitspace/kitspace#89]
I see that the page of my [board](https://kitnic.it/boards/github.com/descampsa/dynamixelshield/) has not been updated with the last changes in my repository.
The readme was updated 6 days ago, so i guess that there is currently no automatic update?

**Comment by kasbah** [comment]
Correct, I pushed an update now.

**Comment by kasbah** [comment]
I've enabled automatic builds so it will be updated daily without my intervention.

**Comment by kasbah** [comment]
This was fixed with #252 and https://github.com/kitspace/kitspace-repo-watcher. It should now take 3 minutes, maybe 10 minutes max for a page to update
